services:
  hummingbot:
    container_name: hummingbot
    image: hummingbot-local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    depends_on:
      - gateway
  #  environment:
  #    - CONFIG_PASSWORD=admin
  #    - CONFIG_FILE_NAME=v2_with_controllers.py
  #    - SCRIPT_CONFIG=conf_v2_with_controllers.yml

  gateway:
    restart: always
    container_name: gateway
    image: hummingbot/gateway:dedust-ton
    ports:
      - "15888:15888"
    volumes:
      - ../gateway/conf:/home/gateway/conf
      - ../gateway/logs:/home/gateway/logs
      - ./certs:/home/gateway/certs
    environment:
      - GATEWAY_PASSPHRASE=admin
      - DEV=true
    network_mode: host
